# -*- coding: utf-8 -*-
"""AND perceptron

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12_7pmSyUf_VcUqZwS_choIoF2MyYmFvT
"""

import numpy as np

# Step function (activation)
def step(x):
    return 1 if x >= 0 else 0

# AND dataset
X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])

y = np.array([0,1,1,1])

# Initialize weights and bias
w = np.zeros(2)   # 2 inputs → 2 weights
b = 0

# Training
lr = 0.1   # learning rate
epochs = 10

for _ in range(epochs):
    for i in range(len(X)):
        z = np.dot(X[i], w) + b   # weighted sum
        y_pred = step(z)

        error = y[i] - y_pred

        # Update weights and bias
        w = w + lr * error * X[i]
        b = b + lr * error

# Testing
print("Final Weights:", w)
print("Final Bias:", b)

print("\nPredictions:")
for i in range(len(X)):
    z = np.dot(X[i], w) + b
    print(X[i], "->", step(z))