# -*- coding: utf-8 -*-
"""AND mcp neuron

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b5rOvF4PTp6cT8ulWhkvjKVvk_-UIddn
"""

# MCP Neuron Implementation for AND Gate

# Step 1: Define MCP neuron function
def mcp_neuron(inputs, weights, threshold):
    # Calculate weighted sum
    summation = 0
    for i in range(len(inputs)):
        summation += inputs[i] * weights[i]

    # Apply threshold (step function)
    if summation >= threshold:
        return 1
    else:
        return 0


# Step 2: Define AND gate parameters
weights = [1, 1]   # w1 = 1, w2 = 1
threshold = 2     # θ = 2


# Step 3: Define input combinations
inputs_list = [
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
]


# Step 4: Test the MCP neuron
print("AND Gate using MCP Neuron:\n")

for inputs in inputs_list:
    output = mcp_neuron(inputs, weights, threshold)
    print(f"Input: {inputs} -> Output: {output}")