# -*- coding: utf-8 -*-
"""CNN for Multiclass Object Classification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-2bsWHiosgq3kA0OC6fJY4-D1U_wlXdL
"""

# CNN for Multiclass Object Classification
# Classification of digits 0 to 9 using Keras API
# Using inbuilt MNIST dataset

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.layers import Flatten, Dense, Dropout
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.datasets import mnist
import matplotlib.pyplot as plt

# -----------------------------------
# Load Inbuilt Dataset (MNIST)
# -----------------------------------
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Reshape data for CNN
x_train = x_train.reshape(-1, 28, 28, 1).astype('float32') / 255
x_test  = x_test.reshape(-1, 28, 28, 1).astype('float32') / 255

# One-hot encoding
y_train = to_categorical(y_train, 10)
y_test  = to_categorical(y_test, 10)

# -----------------------------------
# Build CNN Model
# -----------------------------------
model = Sequential()

# 1st Convolution Layer
model.add(Conv2D(32, kernel_size=(3,3),
                 activation='relu',
                 input_shape=(28,28,1)))

# Max Pooling
model.add(MaxPooling2D(pool_size=(2,2)))

# Dropout
model.add(Dropout(0.25))

# 2nd Convolution Layer
model.add(Conv2D(64, kernel_size=(3,3),
                 activation='relu'))

# Max Pooling
model.add(MaxPooling2D(pool_size=(2,2)))

# Dropout
model.add(Dropout(0.25))

# Flatten Layer
model.add(Flatten())

# Fully Connected Layer
model.add(Dense(128, activation='relu'))

# Dropout
model.add(Dropout(0.5))

# Output Layer (10 classes: 0 to 9)
model.add(Dense(10, activation='softmax'))

# -----------------------------------
# Compile Model
# -----------------------------------
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# -----------------------------------
# Train Model
# -----------------------------------
history = model.fit(x_train, y_train,
                    batch_size=128,
                    epochs=5,
                    validation_data=(x_test, y_test))

# -----------------------------------
# Evaluate Model
# -----------------------------------
loss, acc = model.evaluate(x_test, y_test)

print("\nTest Accuracy:", acc)

# -----------------------------------
# Predict First 5 Images
# -----------------------------------
pred = model.predict(x_test[:5])

for i in range(5):
    plt.imshow(x_test[i].reshape(28,28), cmap='gray')
    plt.title("Predicted Digit = {}".format(pred[i].argmax()))
    plt.show()