# -*- coding: utf-8 -*-
"""Encoder-Decoder

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7X2ztp55Zpr-g8901e2uEGDUjQk9vx-
"""

# Encoder-Decoder Architecture using LSTM for Machine Translation
# English -> French (Toy Example)

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# -----------------------------------
# Sample Dataset
# -----------------------------------
english_sentences = [
    "hi",
    "how are you",
    "i am fine",
    "thank you",
    "good morning",
    "good night",
    "what is your name",
    "my name is john"
]

french_sentences = [
    "salut",
    "comment ca va",
    "je vais bien",
    "merci",
    "bonjour",
    "bonne nuit",
    "comment tu tappelles",
    "mon nom est john"
]

# Decoder needs start/end tokens
target_sentences = ["startseq " + txt + " endseq" for txt in french_sentences]

# -----------------------------------
# Tokenization
# -----------------------------------
eng_tokenizer = Tokenizer()
eng_tokenizer.fit_on_texts(english_sentences)
eng_seq = eng_tokenizer.texts_to_sequences(english_sentences)

fra_tokenizer = Tokenizer()
fra_tokenizer.fit_on_texts(target_sentences)
fra_seq = fra_tokenizer.texts_to_sequences(target_sentences)

# Vocabulary sizes
num_encoder_tokens = len(eng_tokenizer.word_index) + 1
num_decoder_tokens = len(fra_tokenizer.word_index) + 1

# Max lengths
max_encoder_len = max(len(seq) for seq in eng_seq)
max_decoder_len = max(len(seq) for seq in fra_seq)

# Padding
encoder_input_data = pad_sequences(eng_seq, maxlen=max_encoder_len, padding='post')
decoder_input_data = pad_sequences(fra_seq, maxlen=max_decoder_len, padding='post')

# Decoder target data (shift by one step)
decoder_target_data = np.zeros(
    (len(fra_seq), max_decoder_len, num_decoder_tokens),
    dtype='float32'
)

for i, seq in enumerate(fra_seq):
    for t in range(1, len(seq)):
        decoder_target_data[i, t - 1, seq[t]] = 1.0

# -----------------------------------
# Encoder
# -----------------------------------
latent_dim = 256

encoder_inputs = Input(shape=(None,))
enc_emb = tf.keras.layers.Embedding(num_encoder_tokens, latent_dim)(encoder_inputs)

encoder_lstm = LSTM(latent_dim, return_state=True)
_, state_h, state_c = encoder_lstm(enc_emb)

encoder_states = [state_h, state_c]

# -----------------------------------
# Decoder
# -----------------------------------
decoder_inputs = Input(shape=(None,))
dec_emb_layer = tf.keras.layers.Embedding(num_decoder_tokens, latent_dim)
dec_emb = dec_emb_layer(decoder_inputs)

decoder_lstm = LSTM(latent_dim,
                    return_sequences=True,
                    return_state=True)

decoder_outputs, _, _ = decoder_lstm(dec_emb,
                                     initial_state=encoder_states)

decoder_dense = Dense(num_decoder_tokens,
                      activation='softmax')

decoder_outputs = decoder_dense(decoder_outputs)

# -----------------------------------
# Full Model
# -----------------------------------
model = Model([encoder_inputs, decoder_inputs],
              decoder_outputs)

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# -----------------------------------
# Train Model
# -----------------------------------
print("Training Started...\n")

model.fit([encoder_input_data, decoder_input_data],
          decoder_target_data,
          batch_size=2,
          epochs=300,
          verbose=1)

# -----------------------------------
# Model Summary
# -----------------------------------
print("\nModel Summary:")
model.summary()

# -----------------------------------
# Prediction Example
# -----------------------------------
pred = model.predict([encoder_input_data, decoder_input_data])

print("\nPrediction Done")
print("Example Input :", english_sentences[0])
print("Target Output:", french_sentences[0])