# -*- coding: utf-8 -*-
"""explore lib

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V3wVcN6mqqXgK_POALpMoVHkcMFxg88v
"""

# Updated Code for Exploring Deep Learning Libraries
# (Handles missing MXNet safely)

# -----------------------------------
# 1. TensorFlow
# -----------------------------------
import tensorflow as tf

print("TensorFlow Version:", tf.__version__)

a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

print("TensorFlow Matrix Multiplication:")
print(tf.matmul(a, b))


# -----------------------------------
# 2. Keras
# -----------------------------------
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

print("\nKeras Model Summary:")

model = Sequential([
    Input(shape=(4,)),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.summary()


# -----------------------------------
# 3. MXNet (Optional)
# -----------------------------------
try:
    import mxnet as mx
    from mxnet import nd

    print("\nMXNet Version:", mx.__version__)

    x = nd.array([[1, 2], [3, 4]])
    y = nd.array([[5, 6], [7, 8]])

    print("MXNet Matrix Addition:")
    print(x + y)

except ModuleNotFoundError:
    print("\nMXNet is not installed in this system.")


# -----------------------------------
# 4. JAX
# -----------------------------------
try:
    import jax.numpy as jnp

    print("\nJAX Example:")

    p = jnp.array([1, 2, 3])
    q = jnp.array([4, 5, 6])

    print("Dot Product:", jnp.dot(p, q))

except ModuleNotFoundError:
    print("\nJAX is not installed in this system.")


# -----------------------------------
# 5. Hugging Face Transformers
# -----------------------------------
try:
    from transformers import pipeline

    print("\nHugging Face Transformers Example:")

    classifier = pipeline("sentiment-analysis")

    result = classifier("Deep learning is amazing!")

    print(result)

except ModuleNotFoundError:
    print("\nTransformers library is not installed in this system.")