# -*- coding: utf-8 -*-
"""GAN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vXgIPMFUnqlwbOr2qjaLftC2Ttjjkh5f
"""

import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Flatten, Reshape
from keras.layers import LeakyReLU
from keras.datasets import mnist

# Load MNIST
(X_train, _), (_, _) = mnist.load_data()

# Normalize to [-1, 1]
X_train = (X_train.astype(np.float32) - 127.5) / 127.5
X_train = X_train.reshape(X_train.shape[0], 784)

# ---------------------
# Generator
# ---------------------
def build_generator():
    model = Sequential()
    model.add(Dense(128, input_dim=100))
    model.add(LeakyReLU(alpha=0.2))
    model.add(Dense(256))
    model.add(LeakyReLU(alpha=0.2))
    model.add(Dense(784, activation='tanh'))
    return model

# ---------------------
# Discriminator
# ---------------------
def build_discriminator():
    model = Sequential()
    model.add(Dense(256, input_dim=784))
    model.add(LeakyReLU(alpha=0.2))
    model.add(Dense(128))
    model.add(LeakyReLU(alpha=0.2))
    model.add(Dense(1, activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adam')
    return model

# Build models
generator = build_generator()
discriminator = build_discriminator()

# Combine GAN
discriminator.trainable = False

gan = Sequential([generator, discriminator])
gan.compile(loss='binary_crossentropy', optimizer='adam')

# ---------------------
# Training
# ---------------------
epochs = 10000
batch_size = 32

for epoch in range(epochs):

    # Train Discriminator
    idx = np.random.randint(0, X_train.shape[0], batch_size)
    real_imgs = X_train[idx]

    noise = np.random.normal(0, 1, (batch_size, 100))
    fake_imgs = generator.predict(noise, verbose=0)

    d_loss_real = discriminator.train_on_batch(real_imgs, np.ones((batch_size, 1)))
    d_loss_fake = discriminator.train_on_batch(fake_imgs, np.zeros((batch_size, 1)))

    # Train Generator
    noise = np.random.normal(0, 1, (batch_size, 100))
    g_loss = gan.train_on_batch(noise, np.ones((batch_size, 1)))

    # Print progress
    if epoch % 1000 == 0:
        print(f"Epoch {epoch}, D Loss: {d_loss_real + d_loss_fake}, G Loss: {g_loss}")