# -*- coding: utf-8 -*-
"""LSTM GRU

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZAFZ7Z1_mhVTG_ndJnCrYnPgLtH-___a
"""

# -*- coding: utf-8 -*-
"""19_dl_exp6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1isPSjxCqzuTdSNr-D59VtjRD-MbdD3dK
"""

!pip -q install tensorflow

import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, GRU, Embedding, Dropout
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.datasets import reuters
from tensorflow.keras.utils import to_categorical
import matplotlib.pyplot as plt

num_words = 10000
(X_train, y_train), (X_test, y_test) = reuters.load_data(num_words=num_words)

num_classes = int(np.max(y_train) + 1)

print("Train samples:", len(X_train))
print("Test samples:", len(X_test))
print("Classes:", num_classes)

maxlen = 200

X_train = pad_sequences(X_train, maxlen=maxlen)
X_test = pad_sequences(X_test, maxlen=maxlen)

y_train = to_categorical(y_train, num_classes)
y_test = to_categorical(y_test, num_classes)

lstm_model = Sequential([
    Embedding(input_dim=num_words, output_dim=128),
    LSTM(128),
    Dropout(0.5),
    Dense(64, activation='relu'),
    Dense(num_classes, activation='softmax')
])

lstm_model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

print("\n===== LSTM MODEL =====")
lstm_model.summary()

history_lstm = lstm_model.fit(
    X_train, y_train,
    epochs=8,
    batch_size=64,
    validation_split=0.2,
    verbose=1
)

# Evaluate
lstm_loss, lstm_acc = lstm_model.evaluate(X_test, y_test, verbose=0)
print("\n✅ LSTM Test Accuracy:", lstm_acc)

gru_model = Sequential([
    Embedding(input_dim=num_words, output_dim=128),
    GRU(128),
    Dropout(0.5),
    Dense(64, activation='relu'),
    Dense(num_classes, activation='softmax')
])

gru_model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

print("\n===== GRU MODEL =====")
gru_model.summary()

history_gru = gru_model.fit(
    X_train, y_train,
    epochs=8,
    batch_size=64,
    validation_split=0.2,
    verbose=1
)

gru_loss, gru_acc = gru_model.evaluate(X_test, y_test, verbose=0)
print("\n✅ GRU Test Accuracy:", gru_acc)

plt.figure(figsize=(10,5))

plt.plot(history_lstm.history['val_accuracy'], label='LSTM Val Acc')
plt.plot(history_gru.history['val_accuracy'], label='GRU Val Acc')

plt.title("LSTM vs GRU Accuracy")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.legend()
plt.grid()

plt.show()

sample = X_test[0].reshape(1, -1)

lstm_pred = np.argmax(lstm_model.predict(sample), axis=1)[0]
gru_pred = np.argmax(gru_model.predict(sample), axis=1)[0]

print("\nSample Prediction:")
print("LSTM Predicted Class:", lstm_pred)
print("GRU Predicted Class:", gru_pred)

# Minimal user input test
word_index = reuters.get_word_index()
word_index = {k: (v + 3) for k, v in word_index.items()}

def encode(text):
    return [word_index.get(word, 2) for word in text.lower().split()]

user_text = "stock market prices are rising"

seq = encode(user_text)
padded = pad_sequences([seq], maxlen=maxlen)

lstm_pred = np.argmax(lstm_model.predict(padded), axis=1)[0]
gru_pred = np.argmax(gru_model.predict(padded), axis=1)[0]

print("Input:", user_text)
print("LSTM:", lstm_pred)
print("GRU:", gru_pred)