# -*- coding: utf-8 -*-
"""LSTM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dZnfj9qhb4ULidN4WmQ_wKOuG3DMgyXz
"""

# RNN using LSTM for Multiclass Classification on Text Data
# Using Reuters inbuilt dataset (46 classes)

import tensorflow as tf
from tensorflow.keras.datasets import reuters
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

# -----------------------------------
# Load Reuters Dataset
# -----------------------------------
vocab_size = 10000
max_len = 200

(x_train, y_train), (x_test, y_test) = reuters.load_data(num_words=vocab_size)

# Pad sequences
x_train = pad_sequences(x_train, maxlen=max_len)
x_test = pad_sequences(x_test, maxlen=max_len)

# One-hot encode labels
num_classes = 46
y_train = to_categorical(y_train, num_classes)
y_test = to_categorical(y_test, num_classes)

# -----------------------------------
# Build LSTM Model
# -----------------------------------
model = Sequential()

# Embedding Layer
model.add(Embedding(input_dim=vocab_size,
                    output_dim=128,
                    input_length=max_len))

# LSTM Layer
model.add(LSTM(64))

# Output Layer
model.add(Dense(num_classes, activation='softmax'))

# -----------------------------------
# Compile Model
# -----------------------------------
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# -----------------------------------
# Model Summary
# -----------------------------------
print("Model Summary:")
model.summary()

# -----------------------------------
# Train Model
# -----------------------------------
history = model.fit(x_train, y_train,
                    epochs=5,
                    batch_size=64,
                    validation_split=0.2)

# -----------------------------------
# Evaluate Model
# -----------------------------------
loss, acc = model.evaluate(x_test, y_test)

print("\nTest Accuracy:", acc)

# -----------------------------------
# Predict First 5 Test Samples
# -----------------------------------
pred = model.predict(x_test[:5])

for i in range(5):
    print("Sample", i+1)
    print("Predicted Class =", pred[i].argmax())
    print("Actual Class    =", y_test[i].argmax())
    print()