# -*- coding: utf-8 -*-
"""Neural Network using Keras API

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S7eZFmVtx_zr9Dgvfx-aTbB1gKYj9eu3
"""

# Design and Implement Neural Network using Keras API
# Plot model and layers using vis_utils

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.utils import plot_model
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

# -----------------------------------
# a) Design Neural Network using Keras API
# -----------------------------------

model = Sequential([
    Input(shape=(8,)),          # Input layer with 8 neurons
    Dense(16, activation='relu'),
    Dense(12, activation='relu'),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid')
])

# Compile model
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Display Summary
print("Model Summary:")
model.summary()


# -----------------------------------
# b) Plot model using vis_utils
# -----------------------------------

plot_model(model,
           to_file='keras_model.png',
           show_shapes=True,
           show_layer_names=True)

# Display image
img = mpimg.imread('keras_model.png')
plt.figure(figsize=(10,8))
plt.imshow(img)
plt.axis('off')
plt.show()