# -*- coding: utf-8 -*-
"""RNN for Binary Classification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xiQB_EN30lhakrLde0oys6xcrqIWeZDl
"""

# Simple RNN for Binary Classification on Text Data
# Using IMDB Inbuilt Dataset
# Includes Custom Input Review Prediction

import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense
from tensorflow.keras.preprocessing.sequence import pad_sequences
import re

# -----------------------------------
# Load IMDB Dataset
# -----------------------------------
vocab_size = 10000
max_len = 200

(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=vocab_size)

# Pad sequences
x_train = pad_sequences(x_train, maxlen=max_len)
x_test = pad_sequences(x_test, maxlen=max_len)

# -----------------------------------
# Build Simple RNN Model
# -----------------------------------
model = Sequential()

model.add(Embedding(input_dim=vocab_size, output_dim=32, input_length=max_len))
model.add(SimpleRNN(32, activation='tanh'))
model.add(Dense(1, activation='sigmoid'))

# Compile Model
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# -----------------------------------
# Model Summary
# -----------------------------------
print("Model Summary:")
model.summary()

# -----------------------------------
# Train Model
# -----------------------------------
model.fit(x_train, y_train,
          epochs=3,
          batch_size=64,
          validation_split=0.2)

# -----------------------------------
# Evaluate Model
# -----------------------------------
loss, acc = model.evaluate(x_test, y_test)
print("\nTest Accuracy:", acc)

# -----------------------------------
# Get IMDB Word Index
# -----------------------------------
word_index = imdb.get_word_index()

# -----------------------------------
# Encode Custom Review
# -----------------------------------
def encode_review(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z ]', '', text)

    words = text.split()
    encoded = []

    for word in words:
        index = word_index.get(word)

        if index is not None and index < vocab_size:
            encoded.append(index + 3)

    return encoded

# -----------------------------------
# Predict Custom Review
# -----------------------------------
review = input("\nEnter Movie Review: ")

encoded = encode_review(review)

padded = pad_sequences([encoded], maxlen=max_len)

prediction = model.predict(padded)[0][0]

print("\nPrediction Score:", prediction)

if prediction >= 0.5:
    print("Positive Review 😊")
else:
    print("Negative Review 😞")