# -*- coding: utf-8 -*-
"""Transformer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WPdmh3B6FKC-4uh1g2fLIn-vgcQnaBKp
"""

# Transformer-based Text Classification
# Corrected Version (Uses AutoModel instead of TFAutoModel)

# Install if needed:
# !pip install transformers datasets torch -q

import torch
import torch.nn as nn
from transformers import AutoTokenizer, AutoModel
from datasets import load_dataset
from torch.utils.data import DataLoader, TensorDataset
from sklearn.metrics import accuracy_score
import numpy as np

# -----------------------------------
# Load Inbuilt Dataset (AG News)
# -----------------------------------
dataset = load_dataset("ag_news")

train_texts = dataset["train"]["text"][:3000]
train_labels = dataset["train"]["label"][:3000]

test_texts = dataset["test"]["text"][:1000]
test_labels = dataset["test"]["label"][:1000]

class_names = ["World", "Sports", "Business", "Sci/Tech"]

# -----------------------------------
# Load Transformer Model
# -----------------------------------
model_name = "distilbert-base-uncased"

tokenizer = AutoTokenizer.from_pretrained(model_name)
bert = AutoModel.from_pretrained(model_name)

# -----------------------------------
# Tokenization
# -----------------------------------
max_len = 64

def encode(texts):
    return tokenizer(
        texts,
        padding=True,
        truncation=True,
        max_length=max_len,
        return_tensors="pt"
    )

train_enc = encode(train_texts)
test_enc = encode(test_texts)

# -----------------------------------
# Dataset Loader
# -----------------------------------
train_data = TensorDataset(
    train_enc["input_ids"],
    train_enc["attention_mask"],
    torch.tensor(train_labels)
)

test_data = TensorDataset(
    test_enc["input_ids"],
    test_enc["attention_mask"],
    torch.tensor(test_labels)
)

train_loader = DataLoader(train_data, batch_size=16, shuffle=True)
test_loader = DataLoader(test_data, batch_size=16)

# -----------------------------------
# Classification Model
# -----------------------------------
class NewsClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.bert = bert
        self.fc1 = nn.Linear(768, 128)
        self.dropout = nn.Dropout(0.3)
        self.fc2 = nn.Linear(128, 4)

    def forward(self, input_ids, attention_mask):
        output = self.bert(
            input_ids=input_ids,
            attention_mask=attention_mask
        )

        cls = output.last_hidden_state[:,0,:]
        x = torch.relu(self.fc1(cls))
        x = self.dropout(x)
        x = self.fc2(x)

        return x

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = NewsClassifier().to(device)

# -----------------------------------
# Training Setup
# -----------------------------------
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=2e-5)

# -----------------------------------
# Train Model
# -----------------------------------
epochs = 2

for epoch in range(epochs):
    model.train()

    total_loss = 0

    for batch in train_loader:
        input_ids, mask, labels = [x.to(device) for x in batch]

        optimizer.zero_grad()

        outputs = model(input_ids, mask)

        loss = criterion(outputs, labels)

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}")

# -----------------------------------
# Evaluate
# -----------------------------------
model.eval()

preds = []
actual = []

with torch.no_grad():
    for batch in test_loader:
        input_ids, mask, labels = [x.to(device) for x in batch]

        outputs = model(input_ids, mask)

        pred = torch.argmax(outputs, dim=1)

        preds.extend(pred.cpu().numpy())
        actual.extend(labels.cpu().numpy())

acc = accuracy_score(actual, preds)

print("\nTest Accuracy:", acc)

# -----------------------------------
# Predict Sample News
# -----------------------------------
sample = ["Stock market rises after strong company profits"]

enc = encode(sample)

input_ids = enc["input_ids"].to(device)
mask = enc["attention_mask"].to(device)

with torch.no_grad():
    output = model(input_ids, mask)
    pred = torch.argmax(output, dim=1).item()

print("\nNews:", sample[0])
print("Predicted Category:", class_names[pred])