# -*- coding: utf-8 -*-
"""XOR backpropogation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZtUI5EaaMmGs_g2ACsd-DtnBft3fl0Nx
"""

import numpy as np

# XOR inputs
X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])

# XOR outputs
Y = np.array([[0],[1],[1],[0]])

# Sigmoid function
def sigmoid(x):
    return 1/(1+np.exp(-x))

def derivative(x):
    return x*(1-x)

# Initialize weights
input_neurons = 2
hidden_neurons = 2
output_neurons = 1

wh = np.random.uniform(size=(input_neurons, hidden_neurons))
bh = np.random.uniform(size=(1, hidden_neurons))

wo = np.random.uniform(size=(hidden_neurons, output_neurons))
bo = np.random.uniform(size=(1, output_neurons))

lr = 0.5

# Training
for i in range(10000):

    # Forward propagation
    hidden_input = np.dot(X, wh) + bh
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, wo) + bo
    output = sigmoid(final_input)

    # Backpropagation
    error = Y - output
    d_output = error * derivative(output)

    hidden_error = d_output.dot(wo.T)
    d_hidden = hidden_error * derivative(hidden_output)

    # Update weights
    wo += hidden_output.T.dot(d_output) * lr
    bo += np.sum(d_output, axis=0, keepdims=True) * lr

    wh += X.T.dot(d_hidden) * lr
    bh += np.sum(d_hidden, axis=0, keepdims=True) * lr

print("Output after training:")
print(output)